### ISSUE TITLE
0.21.0 unable to fetch index

### ISSUE THREAD

**Issue by dvzrv** [obi1kenobi/cargo-semver-checks#468] opened 2023-06-08 20:24 UTC
### Steps to reproduce the bug with the above code

Hi! I'm currently trying 0.21.0 on Arch Linux, which is built using the Cargo.lock file of the project.

When trying to run it, the process errors on a TLS issue.
This is reproducible building using cargo (`cargo install --locked cargo-semver-checks`) and using the current distribution package.

FTR: 0.20.0 works as intended using the distribution package and building using `cargo install --locked --version "0.20.0" cargo-semver-checks`.

### Actual Behaviour

```
cargo semver-checks check-release
    Updating index
Error: the server did not provide a certificate; class=Ssl (16)

Caused by:
    the server did not provide a certificate; class=Ssl (16)
```

### Expected Behaviour

```
cargo semver-checks check-release
    Updating index
     Parsing alpm-types v0.2.0 (current)
     Parsing alpm-types v0.2.0 (baseline, cached)
    Checking alpm-types v0.2.0 -> v0.2.0 (no change)
   Completed [   0.026s] 43 checks; 42 passed, 1 failed, 0 unnecessary
```

### Generated System Information

cargo semver-checks --bugreport
#### Software version

cargo-semver-checks 0.21.0 (c7102df-modified)

#### Operating system

Linux 6.3.6-arch1-1

#### Command-line

```bash
/home/user/.cargo/bin/cargo-semver-checks semver-checks --bugreport
```

#### cargo version

```
> cargo -V
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

### Additional Context

For reference, this is how the Arch Linux package is built: https://gitlab.archlinux.org/archlinux/packaging/packages/cargo-semver-checks/-/blob/main/PKGBUILD

**Comment by dvzrv** [comment] 2023-06-08 21:02
Downgrading git2 to 0.16.1 seems to fix this issue.

**Comment by obi1kenobi** [comment] 2023-06-08 21:23
An issue like this has popped on and off for some users for a few versions now, and thus far we haven't been able to successfully diagnose the problem since it's coming via a transitive dependency (I believe via `crates_index`).

Some users were able to work around the problem by disabling the `vendored-openssl` feature on `cargo-semver-checks`. That might be worth a try.

It's also interesting that downgrading `git2` seems to fix the problem. Would you mind opening an issue on that crate and linking to this one? I'd open it myself, but I'd just be copy-pasting what you said with no ability to help `git2`'s maintainers if they need more information.

**Comment by obi1kenobi** [comment] 2023-07-28 20:57
Soon — probably as soon as the next release — we plan on switching from `git2` to `gix` for all our uses, so it's possible that whatever issue we were running into here goes away.

When that happens, I'd love it if you could try to reproduce this issue and let me know if it's still happening or can be closed as resolved.

Thanks for your patience on this!

**Comment by obi1kenobi** [comment] 2023-10-05 18:56
In v0.23 we switched to `gix` for git use cases, so we're using completely different networking code and not using `git2` at all.

When you have a second, would you mind taking a look and seeing if this issue has gone away, and if so letting me know if I can close it?

**Comment by obi1kenobi** [comment] 2023-10-12 23:55
Closing on the assumption that the issue is probably gone. Happy to reopen if we have more evidence of the same problem happening.

**Closed by obi1kenobi** 2023-10-12 23:55 UTC
Labels: C-bug

**Comment by dvzrv** [comment] 2023-10-13 07:34
Hey! Sorry for the late reply!

As I have not seen this problem resurface after patching the package for Arch Linux and later on upgrading it, I do believe this issue is indeed solved!

Keep up the good work! It's much appreciated! :tada:
