### ISSUE TITLE
invalid character `@` in pkgid (rust 1.58.1)

### ISSUE THREAD

**Issue by arnaudgolfouse** [obi1kenobi/cargo-semver-checks#444] opened 2023-04-30 09:44 UTC
### Steps to reproduce the bug with the above code

```
git clone "https://gitlab.com/arnaudgolfouse/ielr.git"
cd ielr/
git reset --hard 834cfe85f0e5ddb78acf32c4f2d62c8ff6d110c4
cargo semver-checks check-release
```

### Actual Behaviour

The output of the above commands is:
```text
Error: Failed when running cargo-doc on <...>/ielr/target/semver-checks/local-ielr-0_1_0/Cargo.toml:
error: invalid character `@` in pkgid: `ielr@0.1.0`, characters must be Unicode XID characters (numbers, `-`, `_`, or most letters)
```

### Expected Behaviour

The project is checked without this error

#### Software version

cargo-semver-checks 0.20.0 (e28327b)

#### Operating system

Linux 5.19.0-41-generic

#### Command-line

```bash
/home/arnaud/.cargo/bin/cargo-semver-checks semver-checks --bugreport 
```

#### cargo version

```
> cargo -V 
cargo 1.58.0 (f01b232bc 2022-01-19)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

### Build Configuration

In `.cargo/config.toml`
```toml
[target.'cfg(feature = "cargo-clippy")']
# Catch debugging remnants.
# They cannot be in lib.rs, because of a clippy bug: see <https://github.com/rust-lang/rust-clippy/issues/6610>.
rustflags = [
    "-Wclippy::print_stdout",
    "-Wclippy::print_stderr",
    "-Wclippy::dbg_macro",
]
```

In `rust-toolchain.toml`:
```toml
[toolchain]
channel = "1.58"
components = ["rustfmt", "clippy"]
profile = "minimal"
```

**Comment by obi1kenobi** [comment] 2023-04-30 20:13
Unfortunately, this is due to the Rust version which is older than what cargo-semver-checks supports. It isn't practical from a maintenance point of view in this project to support too wide of a range of Rust versions, since:
- the rustdoc JSON format keeps changing
- older Rust releases have bugs in the generated rustdoc that are only fixed in newer Rust versions
- resources are limited, and every minute spent on older Rust versions is a minute that could have been spent on the ever-growing list of new features requested by the community

As a result, cargo-semver-checks [v0.20 supports Rust 1.65+](https://github.com/obi1kenobi/cargo-semver-checks/releases/tag/v0.20.0), and the future v0.21 supports Rust 1.67+. Technically, this isn't an MSRV in the classical sense: cargo-semver-checks will compile fine on older Rust too — but the rustdoc JSON format it reads must be generated via a sufficiently-new Rust.

I have confirmed that on a newer Rust, semver-checking this crate succeeds without issue:
```
$ cargo semver-checks check-release
    Updating index
     Parsing ielr v0.1.0 (current)
     Parsing ielr v0.1.0 (baseline)
    Checking ielr v0.1.0 -> v0.1.0 (no change)
   Completed [   0.045s] 43 checks; 43 passed, 0 unnecessary
```

I'm sorry if this is not the answer you were hoping for 😔 Is running the check on newer Rust an option in your use case?

**Closed by obi1kenobi** 2023-04-30 20:13 UTC
Labels: C-bug

**Comment by arnaudgolfouse** [comment] 2023-05-01 08:10
I understand, and checking with a newer Rust is perfectly acceptable to me.
Maybe the rust version could be detected, and the error message would tell you that you need at least Rust `1.xx` ? I will try to look into that.

Thank you for your answer !
